name: Hepner

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.9
  - numpy
  - numba
  - scipy
  - pandas
  - scikit-image
  - matplotlib-base
  - pip
  # conda_spec
  - spyder
  - pip:
    # pip_core
    # pip_spec