name: {{ env_name }}

channels:
  - conda-forge

dependencies:
  # conda_core{{ conda_core }}
  # conda_spec{{ conda_spec }}
  # conda_tf_gpu{{ conda_tf_gpu }}
  - pip:
    # pip_core{{ pip_core }}
    # pip_spec{{ pip_spec }}
    # pip_tf_gpu{{ pip_tf_gpu }}